fix find library
Signed-off-by: Alexandra <alexandra.bach@eonerc.rwth-aachen.de>

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches: [ "master" ]
   pull_request:
+    branches: [ "master" ]
 
 env:
   GIT_SUBMODULE_STRATEGY: recursive
@@ -41,12 +42,11 @@ jobs:
   build:
 
     runs-on: ubuntu-latest
-    container: ghcr.io/${{ github.repository_owner }}/fedora
     permissions:
       contents: read
       packages: write
     name: "prepare:docker [${{ matrix.name }}]"
-         
+                    
     steps:
     - name: Checkout
       uses: actions/checkout@v4
@@ -76,6 +76,37 @@ jobs:
         name: build-fedora-examples-cache-${{ github.sha }}
         retention-days: 1
 
-    
+    - name: Log in to GitHub Container Registry
+      uses: docker/login-action@v3
+      with:
+        registry: ghcr.io
+        username: ${{ github.actor }}
+        password: ${{ secrets.GITHUB_TOKEN }}
+        
+    - name: Build und Push Docker image
+      id: fedora
+      uses: docker/build-push-action@v5
+      with:
+        context: .
+        file: packaging/docker/Dockerfile.fedora
+        push: true
+        tags: ghcr.io/${{ github.repository_owner }}/fedora
+        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/fedora:cache
+        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/fedora:cache,mode=max
 
-    
+    - name: Verify build artifacts
+      run: |
+        ls -l build || echo "Build directory not found"
+
+    - name: Set up library path
+      run: |
+        export LD_LIBRARY_PATH=/build/lib:$LD_LIBRARY_PATH
+        echo "LD_LIBRARY_PATH set to $LD_LIBRARY_PATH"
+
+    - name: Verify library
+      run: |
+        ls -l /build/lib/libvillas.so.1 || echo "Library not found"
+
+    - name: Debug build directory
+      run: |
+        find / -name "libvillas.so*" || echo "Library not found"
