add debug command
Signed-off-by: Alexandra <alexandra.bach@eonerc.rwth-aachen.de>

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -84,3 +84,7 @@ jobs:
     - name: Verify library
       run: |
         ls -l /build/lib/libvillas.so.1 || echo "Library not found"
+
+        - name: Debug build directory
+      run: |
+        find / -name "libvillas.so*" || echo "Library not found"
